version: '3'
services:
  broker:
    build: ./broker
    ports:
      - 8080:8080
    container_name: broker
  auldfellas:
    build: ./auldfellas
    container_name: auldfellas
    depends_on:
      - broker
    environment:
      - SERVER_HOST=broker
  dodgydrivers:
    build: ./dodgydrivers
    container_name: dodgydrivers
    depends_on:
      - broker
    environment:
      - SERVER_HOST=broker
  girlpower:
    build: ./girlpower
    container_name: girlpower
    depends_on:
      - broker
    environment:
      - SERVER_HOST=broker


