version: '3'
services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
  broker:
    build: ./broker
    container_name: broker
    depends_on:
      - activemq
    environment:
      - SERVER_HOST=activemq
  auldfellas:
    build: ./auldfellas
    container_name: auldfellas
    depends_on:
      - activemq
    environment:
      - SERVER_HOST=activemq
  dodgydrivers:
    build: ./dodgydrivers
    container_name: dodgydrivers
    depends_on:
      - activemq
    environment:
      - SERVER_HOST=activemq
  girlpower:
    build: ./girlpower
    container_name: girlpower
    depends_on:
      - activemq
    environment:
      - SERVER_HOST=activemq


